### ISSUE TITLE
Implement updated credits list

### ISSUE THREAD

**Issue by Egasuas** [SupraGamesCommunity/Supraland_Maps#10]

**Comment by Egasuas** [comment]
Egasuas
Designer, Producer

KoenigsKind
Programmer

LewisPattJr
Designer, Programmer

Thank you to...
Gludek
Jules
TJ999M
Zookster
...for all of the assets, constructive feedback and media!

And a special thanks to...
Anna
Ben
David
Suart
...from SupraGames for providing data, help and the most wonderful games!

**Comment by LewisPattJr** [comment]
Done.
