### ISSUE TITLE
[BUG] Making window vertically smaller and larger again makes layers UI shrink

### ISSUE THREAD

**Issue by Egasuas** [SupraGamesCommunity/Supraland_Maps#16]
- Happens when you go fullscreen
- Happens when you snap the browser to the side of the screen

**Comment by Egasuas** [comment]
Also happens when you go full screen

**Comment by LewisPattJr** [comment]
Recreated on my machine, will address in next commit by styling to fill 100% of container.

**Comment by LewisPattJr** [comment]
Resolved, commented out original contents of _on_resize_window in styledLayerControl.js.  It's not needed since the layer control is inside a container that already handles sizing.
